# Generated by Django 2.1.4 on 2018-12-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_logup', models.DateTimeField(blank=True, null=True)),
                ('_login', models.DateTimeField(blank=True, null=True)),
                ('_logout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
