# Generated by Django 2.1.1 on 2018-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authapp',
            name='login',
        ),
        migrations.RemoveField(
            model_name='authapp',
            name='logout',
        ),
        migrations.RemoveField(
            model_name='authapp',
            name='logup',
        ),
        migrations.AddField(
            model_name='authapp',
            name='_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authapp',
            name='_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authapp',
            name='_logup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
