# Generated by Django 2.1.1 on 2018-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181011_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
