# Generated by Django 2.1.4 on 2018-12-24 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181219_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 10, 14, 31, 902350, tzinfo=utc)),
        ),
    ]
