# Generated by Django 2.1.1 on 2018-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20181103_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
