# Generated by Django 2.1.1 on 2018-11-22 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20181109_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 8, 7, 49, 802479, tzinfo=utc)),
        ),
    ]
