# Generated by Django 2.1.1 on 2018-11-27 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20181122_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 10, 0, 4, 117063, tzinfo=utc)),
        ),
    ]
