# Generated by Django 2.1.1 on 2018-11-27 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20181127_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 14, 32, 41, 173541, tzinfo=utc)),
        ),
    ]
