# Generated by Django 2.1.1 on 2018-11-27 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20181127_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 16, 35, 22, 815249, tzinfo=utc)),
        ),
    ]
