# Generated by Django 2.1.1 on 2018-11-27 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20181127_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 17, 12, 7, 508335, tzinfo=utc)),
        ),
    ]
