# Generated by Django 2.1.1 on 2018-11-27 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20181127_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 17, 25, 44, 873442, tzinfo=utc)),
        ),
    ]
