# Generated by Django 2.1.1 on 2018-11-29 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20181127_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='NotSet', max_length=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 11, 4, 35, 239688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
