# Generated by Django 2.1.1 on 2018-11-29 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_auto_20181129_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='age',
            new_name='_age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 19, 20, 59, 816642, tzinfo=utc)),
        ),
    ]
