# Generated by Django 2.1.1 on 2018-11-30 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_auto_20181129_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 9, 58, 37, 698881, tzinfo=utc)),
        ),
    ]
