# Generated by Django 2.1.1 on 2018-12-04 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_auto_20181130_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 8, 12, 45, 201885, tzinfo=utc)),
        ),
    ]
