# Generated by Django 2.1.1 on 2018-12-12 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_auto_20181204_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 14, 16, 0, 59156, tzinfo=utc)),
        ),
    ]
