# Generated by Django 2.1.1 on 2018-12-13 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_auto_20181212_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 10, 8, 45, 406445, tzinfo=utc)),
        ),
    ]
