# Generated by Django 2.1.1 on 2018-10-11 08:50

from django.db import migrations

def add_default(apps, schema_editor):
    image = apps.get_model('images', 'Image')
    image.objects.create(
        name='default',
        img='default.jpg'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default,
            lambda x, y: (x, y)
        )
    ]
