# Generated by Django 2.1.4 on 2018-12-19 20:57

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=products.models.default_category, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, default=products.models.default_image, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_marker',
            field=models.ForeignKey(blank=True, default=products.models.default_product_marker, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.ProductMarker'),
        ),
    ]
