# Generated by Django 2.1.1 on 2018-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181011_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='₽', max_length=50),
        ),
    ]
