# Generated by Django 2.1.1 on 2018-10-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
