# Generated by Django 2.1.1 on 2018-11-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181025_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default='media/images/default.jpg', on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
    ]
