# Generated by Django 2.1.1 on 2018-11-02 11:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181102_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=products.models.default_image, on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
    ]
