# Generated by Django 2.1.1 on 2018-11-02 11:28

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181102_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=products.models.default_category, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_marker',
            field=models.ForeignKey(default=products.models.default_product_marker, on_delete=django.db.models.deletion.PROTECT, to='products.ProductMarker'),
        ),
    ]
